extends: "config.base.yaml"

generator_llm:
  type: "openai_like"
  # model_name: "llama-cam"
  # api_base: "https://llm.hpc.cam.ac.uk/v1"
  model_name: "meta-llama/Llama-3.3-70B-Instruct"
  api_base: "http://vllm:8080/v1"
  api_key: "${POLARIS_LLM_API_KEY}"
  request_timeout: 90
  max_retries: 1
  model_kwargs:
    max_tokens: 4000
    temperature: 0.8
    top_p: 0.9
    stop_list: ["\nUser:", "\n\nUser:"]

evaluator_llm:
  type: "OpenAILike"
  model_name: "ibm-granite/granite-3.3-8b-instruct"
  api_base: "http://vllm:8080/v1"
  api_key: "${POLARIS_LLM_API_KEY}"
  model_kwargs:
    temperature: 0
    top_p: 1.0
    max_tokens: 4096
    extra_body:
        guided_decoding_backend: outlines

embedder:
  type: "OpenAILike"
  api_base: "${EMBED_API_BASE}"
  model_name: "Qwen/Qwen3-Embedding-8B"
  api_key: ""
  timeout: 600
  max_retries: 3
  embed_batch_size: 1
  num_workers: 1
  model_kwargs: {}

vector_stores:
  docs:
    collection_name: "support_docs_qwen3_8b"
  tickets:
    collection_name: "support_tickets_turn_based_chunking_qwen_3_8b"

storage_context:
  persist_dir: "/app/persist/turn_based_chunking"

evaluation:
  metrics:
    requested:
      - "context_recall"
      - "faithfulness"
      - "answer_relevancy"
      - "factual_correctness"
  run:
    timeout: 240
    max_retries: 0
    max_workers: 16
